inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

# rspecではネストが長くなるため無効にする
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

# 日本語では〜の場合になるためfalseにする
RSpec/ContextWording:
  Enabled: false

Layout/LineLength:
  Max: 120
