version: '3.8'
services:
  ruby:
    image: ruby:3.3.0-slim
    volumes:
      - ./:/app
    working_dir: /app
    command: bash
    environment:
      AWS_XRAY_DAEMON_ADDRESS: localhost:2000

  collector:
    image: amazon/aws-xray-daemon
    ports:
      - 2000:2000/udp
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    command: ["-o"]
